project:
  type: website
  output-dir: docs

website:
  title: "Althea Marks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: inspiration.qmd
        text: Inspiration

format:
  html:
    theme: Lux
    css: styles.css
    toc: true



