project:
  type: website
  output-dir: docs

website:
  title: "Althea Marks"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: talks.qmd
        text: Talks
  repo-url: https://github.com/theamarks/theamarks.github.io

format:
  html:
    theme: Lux
    css: styles.css



